[master]
k3s-master ansible_host=192.168.56.101 ansible_user=ubuntu

[workers]
k3s-worker-1 ansible_host=192.168.56.102 ansible_user=ubuntu
k3s-worker-2 ansible_host=192.168.56.103 ansible_user=ubuntu

[k3s_cluster:children]
master
workers
