apiVersion: v1
kind: Pod
metadata:
  name: storage-test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /data
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: cloudvault-storage-pvc
