apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-storage
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
reclaimPolicy: Delete
volumeBindingMode: Immediate
